### ISSUE TITLE
step-by-step by geoconnex + nldi

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#113]
Want to work up a high level step-by-step for folks wanting to connect to both nldi and geoconnex. Inspired by USBR RISE, who is enthusiastic #81 

WIP

something like

1. Catalog all your locations. 
2. Make landing pages for those locations
3. Mint PIDS for the locations
4. embed JSON-LD according to an appropriate template (#106 )
5. Use hydrolink to add address
6. Assemble into a geojson in NLDI contribution format
7. Publish geojson w/ accessible URL somehow
8. Add to NLDI tsv

**Comment by dblodgett-usgs** [comment]
What format are you thinking for the documentation?

**Comment by ksonda** [comment]
Hadn't got that far, just wanted to figure out a cogent story first. My advice to Allison went all over the place. Could just be a web page. Could be a whole vignette

**Comment by dblodgett-usgs** [comment]
Got it. Re: the cogent story, the issue is it is so specific to a given data providers circumstances. 

In general, what you describe is good. I might separate things into two tracks -- one that revolves around the locations described uniquely and fully and another that revolves around a spatial table with network locations. The two join on the geoconnex.us URI. Ideally, the two are actually, in some way related through automated means (an export from the same backing database for example) but that is where things are going to be different depending on the system in question. 

From a public facing perspective, what we need put in place is, as you described, landing pages and a geoJSON summary table. 

Not sure this is helpful, just thinking allowed. Maybe we write up a three-pronged doc, "what is required to make this work?" -- "what is the start from scratch path that makes sense?" -- "what are some common exceptions to the happy path?"

**Comment by ksonda** [comment]
```Maybe we write up a three-pronged doc, "what is required to make this work?" -- "what is the start from scratch path that makes sense?" -- "what are some common exceptions to the happy path?"```

Yeah this makes sense to me.

1. Reccomended scratch path

and the track for "locations described uniquely"
2. My data is not online in a spatial format (e.g., not online at all, or in an excel file)
3. My data is "available" from a "data portal" (e.g. R shiny apps, ESRI Web Apps, Tableau, PowerBI)
4. I have a bulk file I can make available for download from a data catalog somewhere.
5. I have a spatial feature service (ESRI or similar) or other API but not landing pages
6. I have a spatial feature service (ESRI or similar) or other API and landing pages being generated dynamically

and the track for "spatial table with network locations"
2. I have some kind of spatial summary-level like HUCs, NHD catchments or stream segments, or custom areas
3. I have lat/lon point data
4. I have data with NHDPlus addresses
5. I have data with NHDHR addresses
