### ISSUE TITLE
repo organization

### ISSUE THREAD

**Issue by ksonda** [internetofwater/geoconnex.us#27]
Repo getting cluttered.

I propose reorganizing so all namespaces in one subdirectory like so:

e.g.

- namespaces
  - ref (community)
    - huc02
  - org (organizational)
    - usgs
    - nhdplusv2
    - CHyLD

This raises the question. What is the point of the "ref" directory. Is it exclusively for stuff in https://info.geonnex.us, or for any [non-organizational features](https://github.com/internetofwater/geoconnex.us/wiki/Organization-Specific-Resources). If the latter, should nhdplusv2/comid and huc12 be in /ref ? Perhaps #25 will be relevant

**Comment by dblodgett-usgs** [comment]
👍 to moving things into `namespaces`.

I'd like to avoid being strict about the PID structure if we can. nhdplusv2 is a grey area it's not literally an organization but it needs its own name space that nuances the comid and huc12 (etc.) identifiers to that dataset -- thus I put it in its own namespace rather than `ref`.

I've been imagining `ref` be used for things that do not need a namespace -- so for instance `ref` will eventually have `/ref/huc12` but that will contain non-dataset-specific huc12 (or all that ever existed) identifiers. 

Yes -- I need to get #25 done to clarify some of this thinking.

**Comment by dblodgett-usgs** [comment]
I think we could also revisit the decision to put the pid backups and pygeoapi configuration in this repository to clean things up going forward. I've got the move to a namespaces directory pending in my next PR.
