### ISSUE TITLE
Background reference materials for geoconnex?

### ISSUE THREAD

**Issue by dblodgett-usgs** [internetofwater/geoconnex.us#70]
I just ran across this: https://www.westernstateswater.org/wp-content/uploads/2020/06/CO_Roundable_IoW.pdf

We also just had a really topical session (s) at ESIP. 

Should we start a wiki page or something similar to link to the README that would get people more information about this and related projects?

**Comment by ksonda** [comment]
Yeah I think the default README should  be a general description of the aspiration and required technical and social elements with a list of reference links at the bottom. Rather than the w3id-ish process description. That README should be prominently linked but go in namepsaces maybe? Or we can reorganize the repo to have project docs, then pid registry, which contains the current repo.

**Comment by dblodgett-usgs** [comment]
Agreed. Maybe move some stuff to CONTRIBUTING.md? I'll do a quick PR and you can see what you think.

**Comment by ksonda** [comment]
I think the home page should have some general content about the point of geoconnex. Still too much emphasis on the PID registry. People I direct it to are still having a "why?" or "so what?" reaction. Whether that means the home page should be some other website rather than generated from this repository I'm open to.

**Comment by dblodgett-usgs** [comment]
There are some words over in the SELFIE activity plan: https://opengeospatial.github.io/SELFIE/SELFIE_activity_plan

> sustainable and automatable solutions to link multi-disciplinary, multi-organization environmental data without the requirement to transfer custody or burden of maintenance of data

> built on W3C best practices, providing guidance and a common approach for encoding environmental feature data and links between and among features and observational data about them

> Ultimately, this work is intended to satisfy the needs of many use cases and many kinds of features, from disaster response and resilience to environmental health and the built environment.

Also some good words in the executive summary of the SELFIE ER:
http://docs.ogc.org/DRAFTS/20-067.html#_executive_summary

> The business case for the SELFIE can be illustrated considering two use cases: 1) indexing and discovering models and research from public sector, private sector, or academic projects about a particular place or environmental feature. 2) building a federated multi-organization monitoring network in which all member-systems reference common monitored features and are discoverable through a community index.

> These use cases imply needs along several dimensions: . a shared reference network of environmental features, . the ability to use the reference network to index and provide access to information resources from many organizations, . support for multiple disciplines' information models, conceptual models, research topics, and monitoring practices.

**Comment by ksonda** [comment]
Looks pretty good for now
